### ISSUE TITLE
add filetype to the float

### ISSUE THREAD

**Issue by kadimisetty** [ZWindL/orphans.nvim#4]
Please attach a filetype to the float, perhaps something like `orphans`. It is good practice to do so; in my particular case this would be helpful because I use a trailing whitespace highlighter plugin that lights up in orphans float window because there's a lot of trailing whitespace displayed. Having a filetype will allow me to disable my whitespace plugin for this plugin's float window.

**Comment by ZWindL** [comment]
Thanks @kadimisetty for testing, I resolved the defect by adding an option, please have a look at the new version. If it doesn't work, please feel free to reopen this issue.
